WIP: Remove SimpleProofsFromMap
tendermint/go-crypto pull request #123
Opened 2018-06-11 04:23 UTC by Liamsi

resolves #122 

@mossid @cwgoes @sunnya97 does this still work for every use-case of `SimpleProofsFromMap` in the SDK? Do we actually need a `FromMap` method at all? Couldn't we just use the `FromHashers` method instead? 
We could just use a list of KVPairs, extend them to fulfil the Hasher interface and call `SimpleProofsFromHashers` instead. Then we could delete (almost?) everything in [simple_map.go](https://github.com/tendermint/go-crypto/blob/710efe576acfcc22ead7781cec67a1265cbba0b0/merkle/simple_map.go)

2018-06-11 21:56 UTC, cwgoes commented
I don't think there *are* any uses of `SimpleProofsFromMap` in the SDK - @mossid do you use it on your branch?

2018-06-13 21:54 UTC, mossid requested changes
LGTM

2018-06-13 21:54 UTC, mossid commented on merkle/simple_proof.go
> -	sm.Sort()
Shouldn't we add `kvs.Sort()` here instead of making the user of this function handle it?

2018-06-15 03:26 UTC, liamsi commented on merkle/simple_proof.go
> -	sm.Sort()
That's a very good idea. I'm in favour of deleting `SimpleProofsFromMap` and using `SimpleProofsFromHashers` instead as discussed in the issue related to this PR #122. Let me know what you think.

2018-06-20 20:32 UTC, Liamsi commented
This will be worked on after go-crypto was merged into tendermint. Closing for now.

2018-06-20 20:32 UTC, closed without merging